model:
  - name: "jewellery/earing"

    image:
      path: "mathiaschaize.com/upload/shop/earing"
      sort:
        name: "uploaded_at"
        order_by: "desc"
      max_results: 300

    product:
      type: "simple"
      price:
        euro:
          value: 75
          default: true
          currency: EURO
        idr:
          value: 1200000
          currency: IDR

      stock_status: "instock"
      categories:
        - jewellery:
            id: 27
            name: "Jewellery"
            slug: "jewellery"

        - earring:
            id: 29
            name: "Earring"
            slug: "earring"

  - name: "bag"

    image:
      path: "mathiaschaize.com/upload/shop/bag"
      sort:
        name: "uploaded_at"
        order_by: "desc"
      max_results: 300

    product:
      type: "simple"
      price:
        euro:
          value: 75
          default: true
          currency: EURO
        idr:
          value: 1200000
          currency: IDR

      stock_status: "instock"
      categories:
        - bag:
            id: 23
            name: "Bag"
            slug: "bag"

  - name: "clothes/men"

    image:
      path: "mathiaschaize.com/upload/shop/collections/man"
      sort:
        name: "uploaded_at"
        order_by: "desc"
      max_results: 300

    product:
      type: "simple"
      price:
        euro:
          value: 75
          default: true
          currency: EURO
        idr:
          value: 1200000
          currency: IDR

      stock_status: "instock"
      categories:
        - clothes:
            id: 24
            name: "Clothes"
            slug: "clothes"

        - men:
            id: 25
            name: "Men"
            slug: "men"

  - name: "clothes/women"

    image:
      path: "mathiaschaize.com/upload/shop/collections/women"
      sort:
        name: "uploaded_at"
        order_by: "desc"
      max_results: 300

    product:
      type: "simple"
      price:
        euro:
          value: 75
          default: true
          currency: EURO
        idr:
          value: 1200000
          currency: IDR

      stock_status: "instock"
      categories:
        - clothes:
            id: 24
            name: "Clothes"
            slug: "clothes"

        - women:
            id: 26
            name: "Women"
            slug: "women"
